services:
  frontend:
    container_name: frontend-dev
    extends:
      file: compose.prod.yaml
      service: frontend
    build:
      target: development
    volumes:
      - ./frontend:/app/frontend

  backend:
    container_name: backend-dev
    extends:
      file: compose.prod.yaml
      service: backend
    build:
      target: development
    volumes:
      - ./backend:/app/backend

  nginx:
    container_name: nginx-dev
    extends:
      file: compose.prod.yaml
      service: nginx

volumes:
  static:
  database:
