services:
  frontend:
    container_name: frontend-prod
    build:
      context: ./frontend
      target: production
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    container_name: backend-prod
    build:
      context: ./backend
      target: production
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    volumes:
      - static:/app/backend/static
      - database:/app/backend/database
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env

  nginx:
    container_name: nginx-prod
    build:
      context: ./nginx
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    volumes:
      - static:/app/backend/static
      - database:/app/backend/database/db.sqlite3
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  static:
  database:
