services:
  frontend:
    container_name: frontend-prod
    build:
      context: ./frontend
      target: production
      platforms:
        - "linux/amd64"
    image: amyr11/django-react-app:frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    container_name: backend-prod
    build:
      context: ./backend
      target: production
      platforms:
        - "linux/amd64"
    image: amyr11/django-react-app:backend
    volumes:
      - static:/app/backend/static
      - database:/app/backend/database
    ports:
      - 8000:8000

  nginx:
    container_name: nginx-prod
    build:
      context: ./nginx
      platforms:
        - "linux/amd64"
    image: amyr11/django-react-app:nginx
    volumes:
      - static:/app/backend/static
      - database:/app/backend/database/db.sqlite3
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  static:
  database:
